(() => {
'use strict';
const SPANS=[3000,6000,12000,24000],LOOK=.20,TICK=25,START_DELAY=.05;
const HS={
'normal:hitnormal':'./hitsounds/taiko-normal-hitnormal.wav','normal:hitclap':'./hitsounds/taiko-normal-hitclap.wav','normal:hitfinish':'./hitsounds/taiko-normal-hitfinish.wav','normal:hitwhistle':'./hitsounds/taiko-normal-hitwhistle.wav',
'soft:hitnormal':'./hitsounds/taiko-soft-hitnormal.wav','soft:hitclap':'./hitsounds/taiko-soft-hitclap.wav','soft:hitfinish':'./hitsounds/taiko-soft-hitfinish.wav','soft:hitwhistle':'./hitsounds/taiko-soft-hitwhistle.wav'};
const $=id=>document.getElementById(id),el={
oszInput:$('oszInput'),fileName:$('fileName'),status:$('statusBadge'),diff:$('difficultySelect'),songTitle:$('songTitle'),songMeta:$('songMeta'),time:$('timeDisplay'),copyTime:$('copyTimeButton'),start:$('startMarkButton'),end:$('endMarkButton'),length:$('rangeLength'),back:$('backButton'),play:$('playButton'),fwd:$('forwardButton'),seek:$('seekBar'),zoomOut:$('zoomOutButton'),zoomIn:$('zoomInButton'),zoomLabel:$('zoomLabel'),timeline:$('timelineCanvas'),overview:$('overviewCanvas'),purpose:$('purposeSelect'),fade:$('fadeSelect'),preview:$('outputPreview'),copyOut:$('copyOutputButton'),errorCard:$('errorCard'),error:$('errorMessage')};
let zip=null,maps=[],map=null,start=null,end=null,zoom=1,ready=false,seeking=false,raf=0,tDrag=null,oDrag=null;
let ac=null,music=null,musicName='',src=null,playing=false,startCtx=0,startOffset=0,paused=0,gen=0;
let hsBuffers=new Map(),hsLoad=null,hsTimer=null,nextHit=0,scheduled=new Set();
const setStatus=t=>el.status.textContent=t,clearError=()=>{el.errorCard.hidden=true;el.error.textContent='';},fail=m=>{el.error.textContent=m;el.errorCard.hidden=false;setStatus('エラー');};
const dur=()=>music?music.duration:0,clamp=v=>Math.min(Math.max(Number.isFinite(v)?v:0,0),dur()||Infinity),span=()=>SPANS[zoom],validRange=()=>!!(start&&end&&end.time>=start.time),css=(n,d)=>getComputedStyle(document.documentElement).getPropertyValue(n).trim()||d;
function fmt(ms){ms=Math.max(0,Math.floor(Number.isFinite(ms)?ms:0));const m=Math.floor(ms/60000),s=Math.floor(ms%60000/1000),z=ms%1000;return`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}:${String(z).padStart(3,'0')}`}
function fmtOut(ms){const q=Math.max(0,Math.floor((Number.isFinite(ms)?ms:0)/1000)),h=Math.floor(q/3600),m=Math.floor(q%3600/60),s=q%60;return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
const fmtLen=ms=>Number.isFinite(ms)&&ms>=0?`${(ms/1000).toFixed(3)} s`:'—';
function outputText(){if(!map)return'**曲名：—**\n用途：—\n難易度：**—**\n区間：—（Fade-in/out：含まない）';const title=map.metadata.TitleUnicode||map.metadata.Title||'Untitled',diff=map.metadata.Version||'Unknown',purpose=el.purpose.value||'未選択',fade=el.fade.value||'含まない',range=validRange()?`${fmtOut(start.time)}～${fmtOut(end.time)}`:(start&&end?'ENDがSTARTより前です':'未選択');return`**曲名：${title}**\n用途：${purpose}\n難易度：**${diff}**\n区間：${range}（Fade-in/out：${fade}）`}
function updateOutput(){el.preview.textContent=outputText();el.copyOut.disabled=!(map&&el.purpose.value&&validRange())}
function updateRange(){el.start.classList.toggle('marked',!!start);el.end.classList.toggle('marked',!!end);el.start.textContent=start?'START ✓':'START';el.end.textContent=end?'END ✓':'END';el.length.textContent=validRange()?fmtLen(end.time-start.time):'—';updateOutput();drawAll()}
function resetRange(){start=end=null;updateRange()}
function toggleMark(which){if(!map||!music)return;if(which==='start')start=start?null:{time:Math.round(position(true)*1000)};else end=end?null:{time:Math.round(position(true)*1000)};updateRange()}
async function copy(text,button){if(!text)return;try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(text);else{const t=document.createElement('textarea');t.value=text;t.readOnly=true;t.style.cssText='position:fixed;opacity:0';document.body.appendChild(t);t.select();if(!document.execCommand('copy'))throw 0;t.remove()}if(button){const old=button.textContent;button.textContent='COPIED';setTimeout(()=>button.textContent=old,700)}}catch{fail(`コピーできませんでした。\n${text}`)}}
function kv(line){const i=line.indexOf(':');return i<0?null:[line.slice(0,i).trim(),line.slice(i+1).trim()]}
function hsData(raw){const f=String(raw||'').split(':');return{normalSet:+f[0]||0,additionSet:+f[1]||0,volume:+f[3]||0}}
const setNo=v=>String(v||'').toLowerCase()==='soft'?2:String(v||'').toLowerCase()==='drum'?3:1;
function timingAt(a,t){let lo=0,hi=a.length;while(lo<hi){const m=(lo+hi)>>1;if(a[m].time<=t)lo=m+1;else hi=m}return lo?a[lo-1]:null}
function enrich(m){const def=setNo(m.general.SampleSet);for(const h of m.hits){const tp=timingAt(m.timing,h.time),ts=tp&&tp.sampleSet?tp.sampleSet:def,sd=h.sample,os=h.sampleName==='hitnormal'?sd.normalSet:sd.additionSet,r=os||ts||def;h.family=r===2?'soft':'normal';h.volume=Math.max(0,Math.min(100,sd.volume||(tp?tp.volume:100)||100))}}
function parseOsu(text,fileName){const m={fileName,general:{},metadata:{},difficulty:{},timing:[],hits:[],mode:-1};let sec='';text.replace(/^\uFEFF/,'').split(/\r?\n/).forEach((raw,order)=>{const line=raw.trim();if(!line||line.startsWith('//'))return;if(line[0]==='['&&line.endsWith(']')){sec=line;return}if(sec==='[General]'||sec==='[Metadata]'||sec==='[Difficulty]'){const p=kv(line);if(!p)return;const[k,v]=p;(sec==='[General]'?m.general:sec==='[Metadata]'?m.metadata:m.difficulty)[k]=v;return}if(sec==='[TimingPoints]'){const f=line.split(',');if(f.length<8)return;const time=+f[0],beat=+f[1],meter=parseInt(f[2],10)||4,sampleSet=parseInt(f[3],10)||0,volume=parseInt(f[5],10),uninherited=parseInt(f[6],10)||0,effects=parseInt(f[7],10)||0;if(Number.isFinite(time))m.timing.push({time,beat:Number.isFinite(beat)?beat:0,meter,sampleSet,volume:Number.isFinite(volume)?volume:100,uninherited,effects,order});return}if(sec==='[HitObjects]'){const f=line.split(','),time=parseInt(f[2],10),type=parseInt(f[3],10)||0,sound=parseInt(f[4],10)||0;if(!Number.isFinite(time)||(type&1)===0)return;const ka=(sound&(2|8))!==0,big=(sound&4)!==0;let sampleName='hitnormal';if(ka&&big)sampleName='hitwhistle';else if(ka)sampleName='hitclap';else if(big)sampleName='hitfinish';m.hits.push({time,kind:ka?'ka':'don',big,sampleName,sample:hsData(f[5]||''),family:'normal',volume:100})}});m.mode=parseInt(m.general.Mode??'-1',10);m.timing.sort((a,b)=>a.time-b.time||a.order-b.order);m.hits.sort((a,b)=>a.time-b.time);enrich(m);return m}
function kiai(){if(!map)return[];const out=[];let on=false,s=null;for(const tp of map.timing){const n=(tp.effects&1)!==0;if(n===on)continue;if(on&&s!==null&&tp.time>s)out.push({start:s,end:tp.time});on=n;s=n?tp.time:null}if(on&&s!==null)out.push({start:s,end:music?dur()*1000:Infinity});return out}
const norm=n=>String(n||'').replace(/\\/g,'/').replace(/^\.\//,'').toLowerCase();
function zipFile(name){if(!zip||!name)return null;return zip.file(name)||Object.values(zip.files).find(e=>!e.dir&&norm(e.name)===norm(name))||null}
async function context(resume=false){const C=window.AudioContext||window.webkitAudioContext;if(!C)throw new Error('Web Audio APIに対応していません。');if(!ac)ac=new C({latencyHint:'interactive'});if(resume&&ac.state==='suspended')await ac.resume();return ac}
async function loadHits(){await context();if(!hsLoad)hsLoad=(async()=>{const rows=await Promise.all(Object.entries(HS).map(async([k,u])=>{const r=await fetch(u,{cache:'force-cache'});if(!r.ok)throw new Error(`ヒットサウンドを読み込めません: ${u}`);const b=await r.arrayBuffer();return[k,await ac.decodeAudioData(b.slice(0))]}));hsBuffers=new Map(rows)})();await hsLoad}
function enginePos(){return playing&&ac?clamp(startOffset+Math.max(0,ac.currentTime-startCtx)):paused}
function audiblePos(){if(!playing||!ac)return paused;let c=ac.currentTime;try{if(typeof ac.getOutputTimestamp==='function'){const t=ac.getOutputTimestamp();if(t&&Number.isFinite(t.contextTime)&&t.contextTime>0)c=t.contextTime}else if(Number.isFinite(ac.outputLatency))c=Math.max(0,ac.currentTime-ac.outputLatency)}catch{}return clamp(startOffset+Math.max(0,c-startCtx))}
const position=ui=>ui?audiblePos():enginePos;
function lowerHit(ms){let lo=0,hi=map?map.hits.length:0;while(lo<hi){const m=(lo+hi)>>1;if(map.hits[m].time<ms)lo=m+1;else hi=m}return lo}
function stopScheduled(){for(const s of scheduled)try{s.stop()}catch{}scheduled.clear()}
function stopHitLoop(){if(hsTimer){clearInterval(hsTimer);hsTimer=null}stopScheduled()}
function scheduleHit(h,when){const b=hsBuffers.get(`${h.family}:${h.sampleName}`)||hsBuffers.get(`normal:${h.sampleName}`);if(!b)return;const s=ac.createBufferSource(),g=ac.createGain();s.buffer=b;g.gain.value=h.volume/100;s.connect(g).connect(ac.destination);scheduled.add(s);s.onended=()=>scheduled.delete(s);s.start(when)}
function hitTick(){if(!playing||!map||!ac||!hsBuffers.size)return;const horizon=ac.currentTime+LOOK;while(nextHit<map.hits.length){const h=map.hits[nextHit],target=startCtx+(h.time/1000-startOffset);if(target>horizon)break;if(target>=ac.currentTime-.01)scheduleHit(h,Math.max(target,ac.currentTime+.003));nextHit++}}
function startHitLoop(){stopHitLoop();nextHit=map?lowerHit(startOffset*1000-8):0;hitTick();hsTimer=setInterval(hitTick,TICK)}
function stopSource(){gen++;if(src){try{src.stop()}catch{}try{src.disconnect()}catch{}src=null}stopHitLoop();playing=false;el.play.textContent='▶'}
async function play(){if(!map||!music)return;await context(true);await loadHits();if(paused>=dur()-.001)paused=0;stopSource();const g=++gen,s=ac.createBufferSource(),when=ac.currentTime+START_DELAY;s.buffer=music;s.connect(ac.destination);startCtx=when;startOffset=clamp(paused);src=s;playing=true;el.play.textContent='❚❚';s.onended=()=>{if(g!==gen||s!==src)return;const ended=enginePos()>=dur()-.03;src=null;playing=false;stopHitLoop();if(ended)paused=dur();el.play.textContent='▶';drawAll()};s.start(when,startOffset);startHitLoop()}
function pause(){if(!playing)return;paused=enginePos();stopSource()}
async function seekTo(v){const n=clamp(v),was=playing;if(was)pause();paused=n;if(was)await play();drawAll()}
async function loadMusic(m){const name=m.general.AudioFilename;if(!name)throw new Error('AudioFilenameがありません。');await context();if(music&&musicName===norm(name)){stopSource();paused=0;return}const e=zipFile(name);if(!e)throw new Error(`OSZ内で音源を見つけられません: ${name}`);stopSource();music=null;musicName='';paused=0;const raw=await e.async('arraybuffer');music=await ac.decodeAudioData(raw.slice(0));musicName=norm(name)}
function controls(v){ready=v;[el.play,el.back,el.fwd,el.seek,el.copyTime,el.start,el.end].forEach(n=>n.disabled=!v);updateZoom();updateOutput()}
async function useMap(i){clearError();stopSource();map=maps[i];if(!map)return;resetRange();setStatus('音源解析中');controls(false);try{await loadMusic(map);const title=map.metadata.TitleUnicode||map.metadata.Title||'Untitled',artist=map.metadata.ArtistUnicode||map.metadata.Artist||'Unknown artist';el.songTitle.textContent=`${artist} - ${title}`;el.songMeta.textContent=`${map.hits.length} hits`;el.seek.max=String(dur());el.seek.value='0';el.time.textContent='00:00:000';controls(true);setStatus('準備完了');drawAll()}catch(e){fail(e instanceof Error?e.message:String(e))}}
async function loadOsz(file){clearError();if(!file||!/\.osz$/i.test(file.name||'')){fail('.osz / .OSZ ファイルを選択してください。');return}if(!window.JSZip){fail('JSZipを読み込めません。');return}el.purpose.value='';el.fade.value='含まない';zoom=1;stopSource();music=null;musicName='';map=null;resetRange();setStatus('OSZ解析中');controls(false);el.diff.disabled=true;el.fileName.textContent=file.name;try{zip=await JSZip.loadAsync(file);const es=Object.values(zip.files).filter(e=>!e.dir&&/\.osu$/i.test(e.name));if(!es.length)throw new Error('OSZ内に .osu がありません。');const parsed=[];for(const e of es)parsed.push(parseOsu(await e.async('string'),e.name));const taiko=parsed.filter(x=>x.mode===1);maps=taiko.length?taiko:parsed;if(!maps.length)throw new Error('表示できる譜面がありません。');el.diff.innerHTML='';maps.forEach((x,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${x.metadata.Version||x.fileName} — ${x.hits.length} hits`;el.diff.appendChild(o)});el.diff.disabled=false;await useMap(0)}catch(e){fail(e instanceof Error?e.message:String(e))}}
function updateZoom(){const h=span()/2000;el.zoomLabel.textContent=`±${Number.isInteger(h)?h.toFixed(0):h.toFixed(1)}s`;el.zoomIn.disabled=!ready||zoom===0;el.zoomOut.disabled=!ready||zoom===SPANS.length-1}
function canvas(c){const r=c.getBoundingClientRect(),d=Math.max(1,window.devicePixelRatio||1),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(c.width!==w||c.height!==h){c.width=w;c.height=h}const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);return{x,w:r.width,h:r.height}}
function beatGrid(x,left,right,xp,w,h){const pts=map?map.timing.filter(t=>t.uninherited===1&&t.beat>0):[];for(let i=0;i<pts.length;i++){const p=pts[i],next=pts[i+1],a=Math.max(left,p.time),b=Math.min(right,next?next.time:right);if(b<=a)continue;const pxBeat=p.beat/span()*w,step=pxBeat<11?Math.ceil(11/Math.max(1,pxBeat)):1,meter=Math.max(1,p.meter||4);let n=Math.ceil((a-p.time)/p.beat),last=Math.floor((b-p.time)/p.beat);for(;n<=last;n+=step){const t=p.time+n*p.beat;if(t<left||t>right)continue;const major=((n%meter)+meter)%meter===0;x.strokeStyle=major?'rgba(255,255,255,.18)':'rgba(255,255,255,.07)';x.lineWidth=major?1.25:1;x.beginPath();x.moveTo(xp(t),0);x.lineTo(xp(t),h);x.stroke()}}}
function drawTimeline(){const{x,w,h}=canvas(el.timeline);x.clearRect(0,0,w,h);x.fillStyle='#101015';x.fillRect(0,0,w,h);if(!map)return;const now=position(true)*1000,s=span(),left=now-s/2,right=now+s/2,xp=t=>(t-left)/s*w;x.fillStyle='rgba(242,209,111,.18)';for(const k of kiai()){const a=Math.max(left,k.start),b=Math.min(right,k.end);if(b>a)x.fillRect(xp(a),0,xp(b)-xp(a),h)}if(validRange()){const a=Math.max(left,start.time),b=Math.min(right,end.time);if(b>a){x.fillStyle='rgba(233,101,165,.07)';x.fillRect(xp(a),0,xp(b)-xp(a),h)}}beatGrid(x,left,right,xp,w,h);const y=Math.round(h*.58);x.strokeStyle='rgba(255,255,255,.11)';x.lineWidth=1;x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke();const don=css('--don','#ef6862'),ka=css('--ka','#69bde0');for(let i=lowerHit(left);i<map.hits.length;i++){const q=map.hits[i];if(q.time>right)break;const r=q.big?21:16;x.fillStyle=q.kind==='ka'?ka:don;x.strokeStyle='rgba(255,255,255,.62)';x.lineWidth=q.big?2.4:1.4;x.beginPath();x.arc(xp(q.time),y,r,0,Math.PI*2);x.fill();x.stroke();if(q.big){x.strokeStyle='rgba(255,255,255,.42)';x.lineWidth=1.5;x.beginPath();x.arc(xp(q.time),y,r-6,0,Math.PI*2);x.stroke()}}const mark=(p,label,c)=>{if(!p||p.time<left||p.time>right)return;const px=xp(p.time);x.save();x.strokeStyle=x.fillStyle=c;x.lineWidth=1.7;x.setLineDash([5,4]);x.beginPath();x.moveTo(px,0);x.lineTo(px,h);x.stroke();x.setLineDash([]);x.font='800 10px sans-serif';x.textAlign=px>w-55?'right':'left';x.textBaseline='top';x.fillText(label,px>w-55?px-4:px+4,5);x.restore()};mark(start,'START',css('--range-start','#68d39a'));mark(end,'END',css('--range-end','#f3b55d'));x.strokeStyle='rgba(255,255,255,.98)';x.lineWidth=2;x.beginPath();x.moveTo(w/2,0);x.lineTo(w/2,h);x.stroke()}
function drawOverview(){const{x,w,h}=canvas(el.overview);x.clearRect(0,0,w,h);x.fillStyle='#101015';x.fillRect(0,0,w,h);if(!map||!music||dur()<=0)return;const d=dur()*1000,xp=t=>Math.max(0,Math.min(w,t/d*w));x.fillStyle='rgba(242,209,111,.34)';for(const k of kiai()){const e=Number.isFinite(k.end)?k.end:d;x.fillRect(xp(k.start),0,Math.max(1,xp(e)-xp(k.start)),h)}if(validRange()){x.fillStyle='rgba(233,101,165,.14)';x.fillRect(xp(start.time),0,Math.max(1,xp(end.time)-xp(start.time)),h)}const mk=(p,c)=>{if(!p)return;const px=xp(p.time);x.strokeStyle=c;x.lineWidth=2;x.beginPath();x.moveTo(px,0);x.lineTo(px,h);x.stroke()};mk(start,css('--range-start','#68d39a'));mk(end,css('--range-end','#f3b55d'));const now=xp(position(true)*1000);x.strokeStyle='#fff';x.lineWidth=2;x.beginPath();x.moveTo(now,0);x.lineTo(now,h);x.stroke()}
const drawAll=()=>{drawTimeline();drawOverview()};
function frame(){const p=position(true);el.time.textContent=fmt(p*1000);if(!seeking&&music)el.seek.value=String(p);if(playing&&enginePos()>=dur()-.002){paused=dur();stopSource()}drawAll();raf=requestAnimationFrame(frame)}
async function seekTimeline(e,anchor){const r=el.timeline.getBoundingClientRect(),q=Math.min(1,Math.max(0,(e.clientX-r.left)/r.width));await seekTo((anchor+(q-.5)*span())/1000)}
async function seekOverview(e){const r=el.overview.getBoundingClientRect(),q=Math.min(1,Math.max(0,(e.clientX-r.left)/r.width));await seekTo(dur()*q)}
el.oszInput.addEventListener('change',async e=>{const f=e.target.files&&e.target.files[0];if(f)await loadOsz(f);e.target.value=''});el.diff.addEventListener('change',async()=>{pause();await useMap(+el.diff.value)});el.play.addEventListener('click',async()=>{try{playing?pause():await play()}catch(e){fail(e instanceof Error?e.message:'再生できませんでした。')}});el.back.addEventListener('click',()=>seekTo(position(false)-5));el.fwd.addEventListener('click',()=>seekTo(position(false)+5));
el.zoomOut.addEventListener('click',()=>{zoom=Math.min(SPANS.length-1,zoom+1);updateZoom();drawTimeline()});el.zoomIn.addEventListener('click',()=>{zoom=Math.max(0,zoom-1);updateZoom();drawTimeline()});el.seek.addEventListener('pointerdown',()=>seeking=true);el.seek.addEventListener('pointerup',()=>seeking=false);el.seek.addEventListener('input',()=>{const v=+el.seek.value;if(Number.isFinite(v))seekTo(v)});el.copyTime.addEventListener('click',()=>copy(fmt(position(true)*1000),el.copyTime));el.start.addEventListener('click',()=>toggleMark('start'));el.end.addEventListener('click',()=>toggleMark('end'));el.purpose.addEventListener('change',updateOutput);el.fade.addEventListener('change',updateOutput);el.copyOut.addEventListener('click',()=>copy(outputText(),el.copyOut));
el.timeline.addEventListener('pointerdown',e=>{if(!map||!music)return;tDrag={id:e.pointerId,anchor:position(false)*1000};el.timeline.setPointerCapture?.(e.pointerId);seekTimeline(e,tDrag.anchor)});el.timeline.addEventListener('pointermove',e=>{if(tDrag&&tDrag.id===e.pointerId)seekTimeline(e,tDrag.anchor)});['pointerup','pointercancel'].forEach(n=>el.timeline.addEventListener(n,e=>{if(tDrag&&tDrag.id===e.pointerId)tDrag=null}));el.overview.addEventListener('pointerdown',e=>{if(!map||!music)return;oDrag=e.pointerId;el.overview.setPointerCapture?.(e.pointerId);seekOverview(e)});el.overview.addEventListener('pointermove',e=>{if(oDrag===e.pointerId)seekOverview(e)});['pointerup','pointercancel'].forEach(n=>el.overview.addEventListener(n,e=>{if(oDrag===e.pointerId)oDrag=null}));window.addEventListener('resize',drawAll);window.addEventListener('orientationchange',drawAll);
updateZoom();updateRange();raf=requestAnimationFrame(frame);window.addEventListener('beforeunload',()=>{cancelAnimationFrame(raf);stopSource();if(ac)ac.close().catch(()=>{})});
})();
